# Configuration du plugin DanseAvecLaStare
# Cette version sera mise à jour automatiquement lors du déploiement de nouvelles versions
configVersion: "1.2"

useModelEngine: true

# Mode de secours pour les clients avec shaders / packs fragiles.
# true = charge un blueprint alternatif plus simple et applique les textures de façon dynamique.
modelEngine:
  useFallbackMode: false
  fallbackModelId: joueur_fallback


# Configuration des dances - Chaque style de danse est défini ici
# Ajoute une nouvelle danse sans modifier le code Java, juste la config !
dances:
  twist:
    displayName: "Twist"
    modelId: danseur
    animationName: dance
    movementType: dynamic

  dj:
    displayName: "DJ"
    modelId: dj_animation1
    animationName: dance
    movementType: dynamic
    
  floss:
    displayName: "floss"
    modelId: player_floss
    animationName: dance
    movementType: dynamic

  macarena:
    displayName: "macarena"
    modelId: player_macarena
    animationName: dance
    movementType: dynamic

  dj2:
    displayName: "DJ2"
    modelId: dj_animation2
    animationName: dance
    movementType: dynamic