# Strategy switch
# true = use ModelEngine when plugin is present
# false = fallback to Citizens implementation
useModelEngine: true

modelEngine:
  defaultModelId: danseur
  styleModels:
    twist: danseur
    spin: danseur
    dj: dj_animation1