main: me.utruna.danse.DanseAvecLaStare
version: 2.0.0
name: DanseAvecLaStare
author: Utruna
api-version: 1.21
softdepend: [Citizens, ModelEngine]
commands:
  danse:
    description: Lance ou arrête une danse
    usage: /danse [twist|dj|list|stop|debug]