main: me.utruna.danse.DanseAvecLaStare
version: 1.0.0-SNAPSHOT
name: DanseAvecLaStare
author: Utruna
api-version: 1.21
softdepend: [Citizens, ModelEngine]
commands:
  danse:
    description: Lance ou arrête une danse
    usage: /danse [twist|spin|disco|moonwalk|wave|list|stop|debug]