package me.utruna.danse.menu;

public enum MenuType {
    PLAYER_MAIN, PLAYER_STYLES,
    STAFF_MAIN, STAFF_DANCER, STAFF_PLAYLIST, STAFF_CHOREOGRAPHY, STAFF_SKIN_CACHE,
    CHOREO_SELECT_STYLE, CHOREO_CONFIG_TRACK
}
